//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36373
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.36373 版自动生成。
// 
#pragma warning disable 1591

namespace Interfaces.FreshPortSupplierSell {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonInvokeServiceImplSoapBinding", Namespace="http://webservice.novaone.com/")]
    public partial class CommonInvokeServiceImpl : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback suppliersellcheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback takeitemOperationCompleted;
        
        private System.Threading.SendOrPostCallback airdeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback businessOperationCompleted;
        
        private System.Threading.SendOrPostCallback dometicOperationCompleted;
        
        private System.Threading.SendOrPostCallback cargoitemOperationCompleted;
        
        private System.Threading.SendOrPostCallback suppliersellOperationCompleted;
        
        private System.Threading.SendOrPostCallback huodaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback errOperationCompleted;
        
        private System.Threading.SendOrPostCallback domestictakegoodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback returnboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback importfeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncOperationCompleted;
        
        private System.Threading.SendOrPostCallback internalOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletesuppliersellOperationCompleted;
        
        private System.Threading.SendOrPostCallback airdeliveryitemOperationCompleted;
        
        private System.Threading.SendOrPostCallback guoneifeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback cargoOperationCompleted;
        
        private System.Threading.SendOrPostCallback logicitemOperationCompleted;
        
        private System.Threading.SendOrPostCallback intermoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback containerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CommonInvokeServiceImpl() {
            this.Url = global::Interfaces.Properties.Settings.Default.Interfaces_FreshPortSupplierSell_CommonInvokeServiceImpl;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event suppliersellcheckCompletedEventHandler suppliersellcheckCompleted;
        
        /// <remarks/>
        public event takeitemCompletedEventHandler takeitemCompleted;
        
        /// <remarks/>
        public event airdeliveryCompletedEventHandler airdeliveryCompleted;
        
        /// <remarks/>
        public event businessCompletedEventHandler businessCompleted;
        
        /// <remarks/>
        public event dometicCompletedEventHandler dometicCompleted;
        
        /// <remarks/>
        public event cargoitemCompletedEventHandler cargoitemCompleted;
        
        /// <remarks/>
        public event suppliersellCompletedEventHandler suppliersellCompleted;
        
        /// <remarks/>
        public event huodaiCompletedEventHandler huodaiCompleted;
        
        /// <remarks/>
        public event errCompletedEventHandler errCompleted;
        
        /// <remarks/>
        public event domestictakegoodsCompletedEventHandler domestictakegoodsCompleted;
        
        /// <remarks/>
        public event returnboxCompletedEventHandler returnboxCompleted;
        
        /// <remarks/>
        public event importfeeCompletedEventHandler importfeeCompleted;
        
        /// <remarks/>
        public event syncCompletedEventHandler syncCompleted;
        
        /// <remarks/>
        public event internalCompletedEventHandler internalCompleted;
        
        /// <remarks/>
        public event deletesuppliersellCompletedEventHandler deletesuppliersellCompleted;
        
        /// <remarks/>
        public event airdeliveryitemCompletedEventHandler airdeliveryitemCompleted;
        
        /// <remarks/>
        public event guoneifeeCompletedEventHandler guoneifeeCompleted;
        
        /// <remarks/>
        public event cargoCompletedEventHandler cargoCompleted;
        
        /// <remarks/>
        public event logicitemCompletedEventHandler logicitemCompleted;
        
        /// <remarks/>
        public event intermoneyCompletedEventHandler intermoneyCompleted;
        
        /// <remarks/>
        public event containerCompletedEventHandler containerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string suppliersellcheck(string sd) {
            object[] results = this.Invoke("suppliersellcheck", new object[] {
                        sd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void suppliersellcheckAsync(string sd) {
            this.suppliersellcheckAsync(sd, null);
        }
        
        /// <remarks/>
        public void suppliersellcheckAsync(string sd, object userState) {
            if ((this.suppliersellcheckOperationCompleted == null)) {
                this.suppliersellcheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsuppliersellcheckOperationCompleted);
            }
            this.InvokeAsync("suppliersellcheck", new object[] {
                        sd}, this.suppliersellcheckOperationCompleted, userState);
        }
        
        private void OnsuppliersellcheckOperationCompleted(object arg) {
            if ((this.suppliersellcheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.suppliersellcheckCompleted(this, new suppliersellcheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string takeitem(string xml) {
            object[] results = this.Invoke("takeitem", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void takeitemAsync(string xml) {
            this.takeitemAsync(xml, null);
        }
        
        /// <remarks/>
        public void takeitemAsync(string xml, object userState) {
            if ((this.takeitemOperationCompleted == null)) {
                this.takeitemOperationCompleted = new System.Threading.SendOrPostCallback(this.OntakeitemOperationCompleted);
            }
            this.InvokeAsync("takeitem", new object[] {
                        xml}, this.takeitemOperationCompleted, userState);
        }
        
        private void OntakeitemOperationCompleted(object arg) {
            if ((this.takeitemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.takeitemCompleted(this, new takeitemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string airdelivery(string xml) {
            object[] results = this.Invoke("airdelivery", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void airdeliveryAsync(string xml) {
            this.airdeliveryAsync(xml, null);
        }
        
        /// <remarks/>
        public void airdeliveryAsync(string xml, object userState) {
            if ((this.airdeliveryOperationCompleted == null)) {
                this.airdeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnairdeliveryOperationCompleted);
            }
            this.InvokeAsync("airdelivery", new object[] {
                        xml}, this.airdeliveryOperationCompleted, userState);
        }
        
        private void OnairdeliveryOperationCompleted(object arg) {
            if ((this.airdeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.airdeliveryCompleted(this, new airdeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string business(string xml) {
            object[] results = this.Invoke("business", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void businessAsync(string xml) {
            this.businessAsync(xml, null);
        }
        
        /// <remarks/>
        public void businessAsync(string xml, object userState) {
            if ((this.businessOperationCompleted == null)) {
                this.businessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbusinessOperationCompleted);
            }
            this.InvokeAsync("business", new object[] {
                        xml}, this.businessOperationCompleted, userState);
        }
        
        private void OnbusinessOperationCompleted(object arg) {
            if ((this.businessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.businessCompleted(this, new businessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string dometic(string sd) {
            object[] results = this.Invoke("dometic", new object[] {
                        sd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dometicAsync(string sd) {
            this.dometicAsync(sd, null);
        }
        
        /// <remarks/>
        public void dometicAsync(string sd, object userState) {
            if ((this.dometicOperationCompleted == null)) {
                this.dometicOperationCompleted = new System.Threading.SendOrPostCallback(this.OndometicOperationCompleted);
            }
            this.InvokeAsync("dometic", new object[] {
                        sd}, this.dometicOperationCompleted, userState);
        }
        
        private void OndometicOperationCompleted(object arg) {
            if ((this.dometicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dometicCompleted(this, new dometicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string cargoitem(string xml) {
            object[] results = this.Invoke("cargoitem", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cargoitemAsync(string xml) {
            this.cargoitemAsync(xml, null);
        }
        
        /// <remarks/>
        public void cargoitemAsync(string xml, object userState) {
            if ((this.cargoitemOperationCompleted == null)) {
                this.cargoitemOperationCompleted = new System.Threading.SendOrPostCallback(this.OncargoitemOperationCompleted);
            }
            this.InvokeAsync("cargoitem", new object[] {
                        xml}, this.cargoitemOperationCompleted, userState);
        }
        
        private void OncargoitemOperationCompleted(object arg) {
            if ((this.cargoitemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cargoitemCompleted(this, new cargoitemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string suppliersell(string xml) {
            object[] results = this.Invoke("suppliersell", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void suppliersellAsync(string xml) {
            this.suppliersellAsync(xml, null);
        }
        
        /// <remarks/>
        public void suppliersellAsync(string xml, object userState) {
            if ((this.suppliersellOperationCompleted == null)) {
                this.suppliersellOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsuppliersellOperationCompleted);
            }
            this.InvokeAsync("suppliersell", new object[] {
                        xml}, this.suppliersellOperationCompleted, userState);
        }
        
        private void OnsuppliersellOperationCompleted(object arg) {
            if ((this.suppliersellCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.suppliersellCompleted(this, new suppliersellCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string huodai(string xml) {
            object[] results = this.Invoke("huodai", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void huodaiAsync(string xml) {
            this.huodaiAsync(xml, null);
        }
        
        /// <remarks/>
        public void huodaiAsync(string xml, object userState) {
            if ((this.huodaiOperationCompleted == null)) {
                this.huodaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhuodaiOperationCompleted);
            }
            this.InvokeAsync("huodai", new object[] {
                        xml}, this.huodaiOperationCompleted, userState);
        }
        
        private void OnhuodaiOperationCompleted(object arg) {
            if ((this.huodaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.huodaiCompleted(this, new huodaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string err(string xml) {
            object[] results = this.Invoke("err", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void errAsync(string xml) {
            this.errAsync(xml, null);
        }
        
        /// <remarks/>
        public void errAsync(string xml, object userState) {
            if ((this.errOperationCompleted == null)) {
                this.errOperationCompleted = new System.Threading.SendOrPostCallback(this.OnerrOperationCompleted);
            }
            this.InvokeAsync("err", new object[] {
                        xml}, this.errOperationCompleted, userState);
        }
        
        private void OnerrOperationCompleted(object arg) {
            if ((this.errCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.errCompleted(this, new errCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string domestictakegoods(string xml) {
            object[] results = this.Invoke("domestictakegoods", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void domestictakegoodsAsync(string xml) {
            this.domestictakegoodsAsync(xml, null);
        }
        
        /// <remarks/>
        public void domestictakegoodsAsync(string xml, object userState) {
            if ((this.domestictakegoodsOperationCompleted == null)) {
                this.domestictakegoodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndomestictakegoodsOperationCompleted);
            }
            this.InvokeAsync("domestictakegoods", new object[] {
                        xml}, this.domestictakegoodsOperationCompleted, userState);
        }
        
        private void OndomestictakegoodsOperationCompleted(object arg) {
            if ((this.domestictakegoodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.domestictakegoodsCompleted(this, new domestictakegoodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string returnbox(string xml) {
            object[] results = this.Invoke("returnbox", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void returnboxAsync(string xml) {
            this.returnboxAsync(xml, null);
        }
        
        /// <remarks/>
        public void returnboxAsync(string xml, object userState) {
            if ((this.returnboxOperationCompleted == null)) {
                this.returnboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnboxOperationCompleted);
            }
            this.InvokeAsync("returnbox", new object[] {
                        xml}, this.returnboxOperationCompleted, userState);
        }
        
        private void OnreturnboxOperationCompleted(object arg) {
            if ((this.returnboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnboxCompleted(this, new returnboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string importfee(string xml) {
            object[] results = this.Invoke("importfee", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void importfeeAsync(string xml) {
            this.importfeeAsync(xml, null);
        }
        
        /// <remarks/>
        public void importfeeAsync(string xml, object userState) {
            if ((this.importfeeOperationCompleted == null)) {
                this.importfeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportfeeOperationCompleted);
            }
            this.InvokeAsync("importfee", new object[] {
                        xml}, this.importfeeOperationCompleted, userState);
        }
        
        private void OnimportfeeOperationCompleted(object arg) {
            if ((this.importfeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importfeeCompleted(this, new importfeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool sync(string duserText) {
            object[] results = this.Invoke("sync", new object[] {
                        duserText});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void syncAsync(string duserText) {
            this.syncAsync(duserText, null);
        }
        
        /// <remarks/>
        public void syncAsync(string duserText, object userState) {
            if ((this.syncOperationCompleted == null)) {
                this.syncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncOperationCompleted);
            }
            this.InvokeAsync("sync", new object[] {
                        duserText}, this.syncOperationCompleted, userState);
        }
        
        private void OnsyncOperationCompleted(object arg) {
            if ((this.syncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncCompleted(this, new syncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string @internal(string sd) {
            object[] results = this.Invoke("internal", new object[] {
                        sd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void internalAsync(string sd) {
            this.internalAsync(sd, null);
        }
        
        /// <remarks/>
        public void internalAsync(string sd, object userState) {
            if ((this.internalOperationCompleted == null)) {
                this.internalOperationCompleted = new System.Threading.SendOrPostCallback(this.OninternalOperationCompleted);
            }
            this.InvokeAsync("internal", new object[] {
                        sd}, this.internalOperationCompleted, userState);
        }
        
        private void OninternalOperationCompleted(object arg) {
            if ((this.internalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.internalCompleted(this, new internalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string deletesuppliersell(string xml) {
            object[] results = this.Invoke("deletesuppliersell", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deletesuppliersellAsync(string xml) {
            this.deletesuppliersellAsync(xml, null);
        }
        
        /// <remarks/>
        public void deletesuppliersellAsync(string xml, object userState) {
            if ((this.deletesuppliersellOperationCompleted == null)) {
                this.deletesuppliersellOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletesuppliersellOperationCompleted);
            }
            this.InvokeAsync("deletesuppliersell", new object[] {
                        xml}, this.deletesuppliersellOperationCompleted, userState);
        }
        
        private void OndeletesuppliersellOperationCompleted(object arg) {
            if ((this.deletesuppliersellCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletesuppliersellCompleted(this, new deletesuppliersellCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string airdeliveryitem(string xml) {
            object[] results = this.Invoke("airdeliveryitem", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void airdeliveryitemAsync(string xml) {
            this.airdeliveryitemAsync(xml, null);
        }
        
        /// <remarks/>
        public void airdeliveryitemAsync(string xml, object userState) {
            if ((this.airdeliveryitemOperationCompleted == null)) {
                this.airdeliveryitemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnairdeliveryitemOperationCompleted);
            }
            this.InvokeAsync("airdeliveryitem", new object[] {
                        xml}, this.airdeliveryitemOperationCompleted, userState);
        }
        
        private void OnairdeliveryitemOperationCompleted(object arg) {
            if ((this.airdeliveryitemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.airdeliveryitemCompleted(this, new airdeliveryitemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string guoneifee(string xml) {
            object[] results = this.Invoke("guoneifee", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void guoneifeeAsync(string xml) {
            this.guoneifeeAsync(xml, null);
        }
        
        /// <remarks/>
        public void guoneifeeAsync(string xml, object userState) {
            if ((this.guoneifeeOperationCompleted == null)) {
                this.guoneifeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguoneifeeOperationCompleted);
            }
            this.InvokeAsync("guoneifee", new object[] {
                        xml}, this.guoneifeeOperationCompleted, userState);
        }
        
        private void OnguoneifeeOperationCompleted(object arg) {
            if ((this.guoneifeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guoneifeeCompleted(this, new guoneifeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string cargo(string xml) {
            object[] results = this.Invoke("cargo", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cargoAsync(string xml) {
            this.cargoAsync(xml, null);
        }
        
        /// <remarks/>
        public void cargoAsync(string xml, object userState) {
            if ((this.cargoOperationCompleted == null)) {
                this.cargoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncargoOperationCompleted);
            }
            this.InvokeAsync("cargo", new object[] {
                        xml}, this.cargoOperationCompleted, userState);
        }
        
        private void OncargoOperationCompleted(object arg) {
            if ((this.cargoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cargoCompleted(this, new cargoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string logicitem(string xml) {
            object[] results = this.Invoke("logicitem", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void logicitemAsync(string xml) {
            this.logicitemAsync(xml, null);
        }
        
        /// <remarks/>
        public void logicitemAsync(string xml, object userState) {
            if ((this.logicitemOperationCompleted == null)) {
                this.logicitemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogicitemOperationCompleted);
            }
            this.InvokeAsync("logicitem", new object[] {
                        xml}, this.logicitemOperationCompleted, userState);
        }
        
        private void OnlogicitemOperationCompleted(object arg) {
            if ((this.logicitemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logicitemCompleted(this, new logicitemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string intermoney(string xml) {
            object[] results = this.Invoke("intermoney", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void intermoneyAsync(string xml) {
            this.intermoneyAsync(xml, null);
        }
        
        /// <remarks/>
        public void intermoneyAsync(string xml, object userState) {
            if ((this.intermoneyOperationCompleted == null)) {
                this.intermoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnintermoneyOperationCompleted);
            }
            this.InvokeAsync("intermoney", new object[] {
                        xml}, this.intermoneyOperationCompleted, userState);
        }
        
        private void OnintermoneyOperationCompleted(object arg) {
            if ((this.intermoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.intermoneyCompleted(this, new intermoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.novaone.com/", ResponseNamespace="http://webservice.novaone.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string container(string xml) {
            object[] results = this.Invoke("container", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void containerAsync(string xml) {
            this.containerAsync(xml, null);
        }
        
        /// <remarks/>
        public void containerAsync(string xml, object userState) {
            if ((this.containerOperationCompleted == null)) {
                this.containerOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontainerOperationCompleted);
            }
            this.InvokeAsync("container", new object[] {
                        xml}, this.containerOperationCompleted, userState);
        }
        
        private void OncontainerOperationCompleted(object arg) {
            if ((this.containerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.containerCompleted(this, new containerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void suppliersellcheckCompletedEventHandler(object sender, suppliersellcheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class suppliersellcheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal suppliersellcheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void takeitemCompletedEventHandler(object sender, takeitemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class takeitemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal takeitemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void airdeliveryCompletedEventHandler(object sender, airdeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class airdeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal airdeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void businessCompletedEventHandler(object sender, businessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class businessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal businessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void dometicCompletedEventHandler(object sender, dometicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dometicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dometicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void cargoitemCompletedEventHandler(object sender, cargoitemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cargoitemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cargoitemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void suppliersellCompletedEventHandler(object sender, suppliersellCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class suppliersellCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal suppliersellCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void huodaiCompletedEventHandler(object sender, huodaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class huodaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal huodaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void errCompletedEventHandler(object sender, errCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class errCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal errCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void domestictakegoodsCompletedEventHandler(object sender, domestictakegoodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class domestictakegoodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal domestictakegoodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void returnboxCompletedEventHandler(object sender, returnboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void importfeeCompletedEventHandler(object sender, importfeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importfeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal importfeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void syncCompletedEventHandler(object sender, syncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void internalCompletedEventHandler(object sender, internalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class internalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal internalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void deletesuppliersellCompletedEventHandler(object sender, deletesuppliersellCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deletesuppliersellCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deletesuppliersellCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void airdeliveryitemCompletedEventHandler(object sender, airdeliveryitemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class airdeliveryitemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal airdeliveryitemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void guoneifeeCompletedEventHandler(object sender, guoneifeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guoneifeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guoneifeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void cargoCompletedEventHandler(object sender, cargoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cargoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cargoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void logicitemCompletedEventHandler(object sender, logicitemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logicitemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logicitemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void intermoneyCompletedEventHandler(object sender, intermoneyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class intermoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal intermoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void containerCompletedEventHandler(object sender, containerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class containerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal containerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591